test_that("interp works", {
  expect_error(interpolate_numeric_vector(TRUE))
  expect_identical(interpolate_numeric_vector(numeric()), numeric())
  expect_identical(interpolate_numeric_vector(1), 1)
  expect_identical(interpolate_numeric_vector(2L), 2L)
  expect_identical(interpolate_numeric_vector(NA_integer_), NA_integer_)
  expect_identical(interpolate_numeric_vector(NA_real_), NA_real_)
  expect_identical(interpolate_numeric_vector(NA_integer_, tails = TRUE), NA_integer_)
  expect_identical(interpolate_numeric_vector(NA_real_, tails = TRUE), NA_real_)
  expect_identical(interpolate_numeric_vector(1:10), 1:10)
  expect_identical(interpolate_numeric_vector(1:10), 1:10)
  expect_identical(interpolate_numeric_vector(c(1,NA,3)), c(1,2,3))
  expect_identical(interpolate_numeric_vector(c(1L,NA,3L)), 1:3)
  expect_identical(interpolate_numeric_vector(c(1L,NA,3L), span = 0L), c(1L,NA,3L))
  expect_identical(interpolate_numeric_vector(c(1L,NA,4L)), c(1L,2L,4L))
  expect_identical(interpolate_numeric_vector(c(1,NA,4)), c(1,2.5,4))
  expect_identical(interpolate_numeric_vector(c(1L,NA,5L)), c(1L,3L,5L))
  expect_identical(interpolate_numeric_vector(c(1L,NA,NA,NA,5L)), 1:5)
  expect_identical(interpolate_numeric_vector(c(5L,NA,NA,NA,1L)), 5:1)
  expect_identical(interpolate_numeric_vector(c(1L,rep(NA,7),10L)), c(1L,rep(NA,7),10L))
  expect_identical(interpolate_numeric_vector(c(1L,rep(NA,8),10L), span = 8), 1:10)
  expect_identical(interpolate_numeric_vector(c(rep(NA,2),1:2)), c(rep(NA,2),1:2)) 
  expect_identical(interpolate_numeric_vector(c(rep(NA,2),1:2), tails = TRUE), c(1L,1L,1:2))
  expect_identical(interpolate_numeric_vector(c(1:2, rep(NA,2))), c(1:2, rep(NA,2)))
  expect_identical(interpolate_numeric_vector(c(1:2, rep(NA,2)), tails = TRUE), c(1:2, 2L,2L))
  expect_identical(interpolate_numeric_vector(c(rep(NA,4),1:2), tails = TRUE), c(rep(NA,4),1:2))
  expect_identical(interpolate_numeric_vector(c(rep(NA,4),1:2), tails = TRUE, span = 4), c(rep(1L, 4),1:2))
  expect_identical(interpolate_numeric_vector(c(1:2, rep(NA,4)), tails = TRUE), c(1:2, rep(NA,4)))
  expect_identical(interpolate_numeric_vector(c(1:2, rep(NA,4)), tails = TRUE, span = 4), c(1:2, rep(2L,4)))
  expect_identical(interpolate_numeric_vector(c(NA,2,NA,5,10,NA,NA,NA)), c(NA,2,3.5,5,10,NA,NA,NA))
  expect_identical(interpolate_numeric_vector(c(NA,2,NA,5,10,NA,NA,NA), tails = TRUE), c(2,2,3.5,5,10,10,10,10))
  expect_identical(interpolate_numeric_vector(c(NA,-2,NA)), c(NA, -2, NA))
  expect_error(interpolate_numeric_vector(c(NA,-2,NA), tails = TRUE),"need at least two non-NA values to interpolate")
  expect_identical(interpolate_numeric_vector(c(NA,1:2,NA)), c(NA,1:2,NA))
  expect_identical(interpolate_numeric_vector(c(NA,1:2,NA), tails = TRUE), c(1L,1L,2L,2L))
})
